// import Layout from "@/components/layout/Layout"
// import Category from "@/components/sections/Category"
// import DealProduct1 from "@/components/sections/DealProduct1"
// import Product1 from "@/components/sections/Product1"
// import Shop from "@/components/sections/Shop"
// import Slider1 from "@/components/sections/Slider1"
// export const metadata = {
//   title: 'Ninico - Minimal NextJS React Template',
//   description: 'Generated by create next app',
// }
// export default function Home() {
//     return (
//         <>
//             <Layout headerStyle={1} footerStyle={1}>
//                 <Slider1 />
//                 <Category />
//                 <Product1 />
//                 <DealProduct1 />
//                 <Shop />
//             </Layout>
//         </>
//     )
// }


import Layout from "@/components/layout/Layout"
import Banner1 from "@/components/sections/Banner1"
import Blog1 from "@/components/sections/Blog1"
import Brand1 from "@/components/sections/Brand1"
import Exclusive from "@/components/sections/Exclusive"
import PackageList from "@/components/sections/Packages"
import Product2 from "@/components/sections/Product2"
import Slider2 from "@/components/sections/Slider2"
import Link from "next/link"
export default function Home2() {

    return (
        <>
            <Layout headerStyle={3} footerStyle={1}>
                <Slider2 />
                <PackageList/>
                {/* <Banner1 /> */}
                <Product2 />
                {/* <Exclusive />    */}
                {/* <Blog1 /> */}
                <Brand1 />
            </Layout>
        </>
    )
}